name: Build and Push Base

on:
  push:
    tags:
      - "base-v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: devcontainer/base
  BUILD_CONTEXT: ./base
  FILE_PATH: ./base/Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set lowercase username
        id: lowercase
        run: echo "username=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Docker meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.REGISTRY }}/${{ steps.lowercase.outputs.username }}/${{env.IMAGE_NAME}}

          #   # generate Docker tags based on the following events/attributes
          #   tags: |
          #       type=schedule
          #       type=ref,event=branch
          #       type=ref,event=pr
          #       type=semver,pattern={{version}}
          #       type=semver,pattern={{major}}.{{minor}}
          #       type=semver,pattern={{major}}
          #       type=sha
          tags: |
            type=match,pattern=.*-(v\d+\.\d+\.\d+),group=1
            type=match,pattern=.*-(v\d+\.\d+)\.\d+,group=1
            type=match,pattern=.*-(v\d+)\.\d+\.\d+,group=1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.FILE_PATH }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
